---
title: "Exploratory Data Analysis"
output: github_document
---

install.packages("patchwork")
install.packages("viridis")

## Setting options

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplots.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_continuous = scale_fill_viridis_d
```


## load the dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31")  %>% 
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

weather_df
```

month = lubridate::floor_date(date, unit = "month")) : round date to the month


## 'group_by'

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup(month)
```

